repos:
  - repo: https://github.com/COFFER-S/check-format-tool
    rev: v1.1.1
    hooks:
      - id: code-style
        args: ['--local', '-vf', 'code-style']
        types_or: [c, c++]
      - id: branch-name
        args: ['branch-name']
      - id: commit-message
        args: ['--ci', 'commit-message']
